install.packages("tidyverse")
install.packages("tm")
install.packages("caret")
install.packages("e1071")
install.packages("SnowballC")
library(tidyverse)
library(tm)
library(caret)
library(e1071)
library(SnowballC)
getwd()
setwd("C:/FakeNewsProject")
fake <- read.csv("Fake.csv")
true <- read.csv("True.csv")
fake$label <- "FAKE"
true$label <- "REAL"
data <- rbind(fake, true)
data <- data %>% select(text, label)
data <- na.omit(data)
head(data)
library(tm)
corpus <- Corpus(VectorSource(data$text))
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removeWords, stopwords("english"))
corpus <- tm_map(corpus, stripWhitespace)
dtm <- DocumentTermMatrix(corpus)
dtm <- removeSparseTerms(dtm, 0.99)
data_matrix <- as.data.frame(as.matrix(dtm))
data_matrix$label <- as.factor(data$label)
library(caret)
set.seed(123)
index <- createDataPartition(data_matrix$label, p = 0.8, list = FALSE)
train_scaled <- train
test_scaled <- test
train_scaled[-ncol(train_scaled)] <- scale(train_scaled[-ncol(train_scaled)])
test_scaled[-ncol(test_scaled)] <- scale(test_scaled[-ncol(test_scaled)])
library(e1071)
model <- svm(label ~ ., data = train, kernel = "linear", cost = 10)
pred <- predict(model, test_scaled)
library(caret)
confusionMatrix(pred, test$label)
table_result <- table(Predicted = pred, Actual = test$label)
barplot(table_result, beside = TRUE, col = c("red", "green"), legend = TRUE, main = "Fake News Detection - Confusion Matrix")
library(ggplot2)
df_cm <- as.data.frame(table_result)
ggplot(df_cm, aes(Predicted, Actual, fill = Freq)) + geom_tile() + geom_text(aes(label = Freq)) + scale_fill_gradient(low = "white", high = "blue") + theme_minimal()
